### ISSUE TITLE
Show Found Profanity

### ISSUE THREAD

**Issue by JonPurvis** [JonPurvis/profanify#25]
It would be great if profanity is found, you can see what the profanity is, without having to go looking for it. At the moment we just return

> to not use profanity

and then the line number so you can click through to the line. What would be nice is if instead it said something along the lines of:

> to not use profanity: {Profanity}

**Comment by spoyntersmith** [comment]
@JonPurvis I couldn't find a way of doing this without adding a new Targeted class, I could also style the text to be red and read more like a list if desired like:

`Expected File.php to not have profanity, but found: 'x', 'y' and 'z'`

Please let me know what you think 👍
